In [2]:
import numpy as np

In [3]:
import numpy as np

a = np.array([[
        
            [[9, 20], [13, 31], [8, 21], [13, 25], [9, 29], [15, 20], [10, 25]],
            [[13, 23], [9, 23], [13, 21], [-13, 32], [15, 25], [13, 31], [15, 29]],
            [[9, 24], [6, 26], [79, 30], [10, 30], [7, 30], [12, 22], [11, 32]],
            [[13, 30], [12, 26], [15, 26], [15, 29], [8, 25], [11, 27], [15, 24]]
        
    ],
    
    [
        
            [[6, 20], [13, 32], [13, 28], [15, 25], [10, 31], [12, 23], [13, 30]],
            [[9, 32], [6, 32], [8, 30], [7, 32], [7, 32], [14, 29], [9, 21]],
            [[14, 23], [11, 23], [14, 29], [15, 23], [15, 30], [10, 31], [13, 30]],
            [[13, 24], [10, 29], [12, 24], [6, 31], [13, 31], [13, 29], [7, 25]]
        
    ],
    [
        
            [[8, 18], [4, 19], [6, 18], [2, 22], [2, 18], [2, 5], [21, 5]],
            [[7, 20], [3, 21], [3, 20], [5, 20], [3, 18], [2, 6], [20, 6]],
            [[4, 19], [5, 21], [5, 18], [5, 21], [3, 19], [7, 6], [22, 4]],
            [[8, 22], [2, 20], [2, 22], [4, 20], [7, 22], [7, 2], [22, 5]]
        
    ],
    [
        
            [[7, 22], [10, 19], [-10, 18], [11, 20], [8, 20], [9, 71], [22, 10]],
            [[8, 22], [9, 21], [10, 22], [8, 19], [9, 18], [11, 11], [18, 11]],
            [[8, 21], [11, 20], [8, 22], [10, 18], [7, 18], [7, 7], [19, 7]],
            [[7, 19], [9, 22], [8, 22], [11, 18], [12, 22], [8, 11], [21, 8]]
        
    ]])
print(a)

[[[[  9  20]
   [ 13  31]
   [  8  21]
   [ 13  25]
   [  9  29]
   [ 15  20]
   [ 10  25]]

  [[ 13  23]
   [  9  23]
   [ 13  21]
   [-13  32]
   [ 15  25]
   [ 13  31]
   [ 15  29]]

  [[  9  24]
   [  6  26]
   [ 79  30]
   [ 10  30]
   [  7  30]
   [ 12  22]
   [ 11  32]]

  [[ 13  30]
   [ 12  26]
   [ 15  26]
   [ 15  29]
   [  8  25]
   [ 11  27]
   [ 15  24]]]


 [[[  6  20]
   [ 13  32]
   [ 13  28]
   [ 15  25]
   [ 10  31]
   [ 12  23]
   [ 13  30]]

  [[  9  32]
   [  6  32]
   [  8  30]
   [  7  32]
   [  7  32]
   [ 14  29]
   [  9  21]]

  [[ 14  23]
   [ 11  23]
   [ 14  29]
   [ 15  23]
   [ 15  30]
   [ 10  31]
   [ 13  30]]

  [[ 13  24]
   [ 10  29]
   [ 12  24]
   [  6  31]
   [ 13  31]
   [ 13  29]
   [  7  25]]]


 [[[  8  18]
   [  4  19]
   [  6  18]
   [  2  22]
   [  2  18]
   [  2   5]
   [ 21   5]]

  [[  7  20]
   [  3  21]
   [  3  20]
   [  5  20]
   [  3  18]
   [  2   6]
   [ 20   6]]

  [[  4  19]
   [  5  21]
   [  5  18]
   [  5  21]
   [  3  19]
 

In [4]:
print(a.ndim)
print(a.shape)
np.amax(a)

4
(4, 4, 7, 2)


79

In [5]:
print(a[0:, 0, 0:, 0:])

[[[  9  20]
  [ 13  31]
  [  8  21]
  [ 13  25]
  [  9  29]
  [ 15  20]
  [ 10  25]]

 [[  6  20]
  [ 13  32]
  [ 13  28]
  [ 15  25]
  [ 10  31]
  [ 12  23]
  [ 13  30]]

 [[  8  18]
  [  4  19]
  [  6  18]
  [  2  22]
  [  2  18]
  [  2   5]
  [ 21   5]]

 [[  7  22]
  [ 10  19]
  [-10  18]
  [ 11  20]
  [  8  20]
  [  9  71]
  [ 22  10]]]


In [6]:
print(a[0:, 0:, 1, 0:])

[[[13 31]
  [ 9 23]
  [ 6 26]
  [12 26]]

 [[13 32]
  [ 6 32]
  [11 23]
  [10 29]]

 [[ 4 19]
  [ 3 21]
  [ 5 21]
  [ 2 20]]

 [[10 19]
  [ 9 21]
  [11 20]
  [ 9 22]]]


In [7]:
print(a[1:4:2, 0:, 0:, 1])

[[[20 32 28 25 31 23 30]
  [32 32 30 32 32 29 21]
  [23 23 29 23 30 31 30]
  [24 29 24 31 31 29 25]]

 [[22 19 18 20 20 71 10]
  [22 21 22 19 18 11 11]
  [21 20 22 18 18  7  7]
  [19 22 22 18 22 11  8]]]


In [8]:
c=a[0, 0:, 0:, 0]

b=(a[0, 0:, 0:, 0]) < 8  #filtering mini temp less than 8 degrees.

print(c[b])

[-13   6   7]


In [9]:
# week2,Thur, -13
print(c) # returns 2D array

[[  9  13   8  13   9  15  10]
 [ 13   9  13 -13  15  13  15]
 [  9   6  79  10   7  12  11]
 [ 13  12  15  15   8  11  15]]


In [10]:
d= np.where(c<8)  # return indexes of values according to given condition in where func 
print(d)

(array([1, 2, 2], dtype=int64), array([3, 1, 4], dtype=int64))


In [11]:
days={0:"Mon", 1:"Tues", 2:"Wed", 3:"Thurs", 4:"Fri", 5:"Sat", 6:"Sun"}
for i in range(len(d[0])):
    print('week: ',(d[0][i])+1, 'day: ',days[d[1][i]])

week:  2 day:  Thurs
week:  3 day:  Tues
week:  3 day:  Fri


In [12]:
l=[1,2]  #filtering Dec and Jan months
c=a[l, 0:, 0:, 1]
s=(a[l, 0:, 0:, 1]) > 20
print(c[s])   #returns all those values of max temp who has crossed a threshold of 20 deg.

[32 28 25 31 23 30 32 32 30 32 32 29 21 23 23 29 23 30 31 30 24 29 24 31
 31 29 25 22 21 21 21 22 22 22]


In [13]:
print(c)  #returns 3D

[[[20 32 28 25 31 23 30]
  [32 32 30 32 32 29 21]
  [23 23 29 23 30 31 30]
  [24 29 24 31 31 29 25]]

 [[18 19 18 22 18  5  5]
  [20 21 20 20 18  6  6]
  [19 21 18 21 19  6  4]
  [22 20 22 20 22  2  5]]]


In [14]:
d=np.where(c>20)  #return indexes
print(d)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1], dtype=int64), array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 0, 1, 2, 2, 3, 3, 3], dtype=int64), array([1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 3, 1, 1, 3, 0, 2, 4], dtype=int64))


In [15]:
# for December month
for i in range(len(d[0])):
    print('week: ',d[0][i]+1, " of December month ")
    print('week: ',d[1][i]+1, " of January month ")

week:  1  of December month 
week:  1  of January month 
week:  1  of December month 
week:  1  of January month 
week:  1  of December month 
week:  1  of January month 
week:  1  of December month 
week:  1  of January month 
week:  1  of December month 
week:  1  of January month 
week:  1  of December month 
week:  1  of January month 
week:  1  of December month 
week:  2  of January month 
week:  1  of December month 
week:  2  of January month 
week:  1  of December month 
week:  2  of January month 
week:  1  of December month 
week:  2  of January month 
week:  1  of December month 
week:  2  of January month 
week:  1  of December month 
week:  2  of January month 
week:  1  of December month 
week:  2  of January month 
week:  1  of December month 
week:  3  of January month 
week:  1  of December month 
week:  3  of January month 
week:  1  of December month 
week:  3  of January month 
week:  1  of December month 
week:  3  of January month 
week:  1  of December month 
we

In [16]:
Q1=np.percentile(a,25)                #-1.5*IQR(Q3-Q1)
Q3=np.percentile(a,75)
lower_range=Q1-(1.5*(Q3-Q1))
upper_range=Q3+(1.5*(Q3-Q1))
print("lower range: ", lower_range)
print("upper range: ", upper_range)
upper=a>upper_range
lower=a<lower_range
print("outliers are :")
u=a[upper]
l=a[lower]

    
print(u,l)

if u.all() or l.all():
    print("absured values present in the dataset:")

lower range:  -13.0
upper range:  43.0
outliers are :
[79 71] []
absured values present in the dataset:


In [20]:
a[0, 2, 2, 0] = 50 #updating first outliers
a[3,0,5,1] =  25  #updating second outliers
print(a[0, 2, 2, 0])
print(a[3,0,5,1])

50
25


In [21]:
print(a) # outliers are removed by appropriate values

[[[[  9  20]
   [ 13  31]
   [  8  21]
   [ 13  25]
   [  9  29]
   [ 15  20]
   [ 10  25]]

  [[ 13  23]
   [  9  23]
   [ 13  21]
   [-13  32]
   [ 15  25]
   [ 13  31]
   [ 15  29]]

  [[  9  24]
   [  6  26]
   [ 50  30]
   [ 10  30]
   [  7  30]
   [ 12  22]
   [ 11  32]]

  [[ 13  30]
   [ 12  26]
   [ 15  26]
   [ 15  29]
   [  8  25]
   [ 11  27]
   [ 15  24]]]


 [[[  6  20]
   [ 13  32]
   [ 13  28]
   [ 15  25]
   [ 10  31]
   [ 12  23]
   [ 13  30]]

  [[  9  32]
   [  6  32]
   [  8  30]
   [  7  32]
   [  7  32]
   [ 14  29]
   [  9  21]]

  [[ 14  23]
   [ 11  23]
   [ 14  29]
   [ 15  23]
   [ 15  30]
   [ 10  31]
   [ 13  30]]

  [[ 13  24]
   [ 10  29]
   [ 12  24]
   [  6  31]
   [ 13  31]
   [ 13  29]
   [  7  25]]]


 [[[  8  18]
   [  4  19]
   [  6  18]
   [  2  22]
   [  2  18]
   [  2   5]
   [ 21   5]]

  [[  7  20]
   [  3  21]
   [  3  20]
   [  5  20]
   [  3  18]
   [  2   6]
   [ 20   6]]

  [[  4  19]
   [  5  21]
   [  5  18]
   [  5  21]
   [  3  19]
 

In [22]:
c=a[1, 0:, 0:, 1] # for Dec months of max temp
c=a[2, 0:, 0:, 1] # for Jan months of max temp
print("average of max temp of Dec months of jaipur\n",np.mean(c))
print("average of max temp of Jan months of jaipur\n",np.mean(c))

average of max temp of Dec months of jaipur
 15.607142857142858
average of max temp of Jan months of jaipur
 15.607142857142858


In [23]:
c=a[1, 0:, 0:, 0]
print(c)
print(np.mean(c, axis=1))

[[ 6 13 13 15 10 12 13]
 [ 9  6  8  7  7 14  9]
 [14 11 14 15 15 10 13]
 [13 10 12  6 13 13  7]]
[11.71428571  8.57142857 13.14285714 10.57142857]


In [24]:
l=[1,2]  #filtering Dec and Jan months
c=a[l, 0:, 0:, 1]

print("winter months of Dec and Jan:\n", np.mean(c))

winter months of Dec and Jan:
 21.714285714285715


In [25]:
l=[1,2]  #filtering Dec and Jan months
c=a[l, 0:, 0:, 0]
print("the least temp experienced by the city in the month of Dec and Jan: ",c.min())

#finding indexe of least temp
print("\nindexes when least temp experienced:\n")
d=np.where(c==np.amin(c))
print(d)
months={0:"Nov", 1:"Dec", 2:"Jan", 3:"Feb"}
weeks={0:"week 1", 1:"week 2", 2:"week 3", 3:"week 4"}
days={0:"Mon", 1:"Tues", 2:"Wed", 3:"Thurs", 4:"Fri", 5:"Sat", 6:"Sun"}
print("\nThe exact date when least temp experienced by the city in the months of dec and jan.:\n")
for i in range(len(d[0])):
    print(days[d[2][i]], "/",weeks[d[1][i]],"/", months[d[0][i]])

the least temp experienced by the city in the month of Dec and Jan:  2

indexes when least temp experienced:

(array([1, 1, 1, 1, 1, 1], dtype=int64), array([0, 0, 0, 1, 3, 3], dtype=int64), array([3, 4, 5, 5, 1, 2], dtype=int64))

The exact date when least temp experienced by the city in the months of dec and jan.:

Thurs / week 1 / Dec
Fri / week 1 / Dec
Sat / week 1 / Dec
Sat / week 2 / Dec
Tues / week 4 / Dec
Wed / week 4 / Dec


In [26]:
c=a[3, 0:, 0:, 1]
# print("max temp in the month of Feb: ", np.max(c))
x=np.where(c==np.max(c))
print(x)
days={0:"Mon", 1:"Tues", 2:"Wed", 3:"Thurs", 4:"Fri", 5:"Sat", 6:"Sun"}
print("Maximum Temperature in the month of Feb is ", np.max(c),"in",days[x[1][0]], "/",x[0][0], "/Feb")

(array([0], dtype=int64), array([5], dtype=int64))
Maximum Temperature in the month of Feb is  25 in Sat / 0 /Feb


In [27]:
c=a[0, 0:, 0:, 1] #for the month of Nov
d=c<c.mean()
print("the max temp of the day dropped below the avg temp of the month of Nov: ", c[d])

id=np.where(d)  #finding the indexes of the temp below than avg temp of month
print(id)

days={0:"Mon", 1:"Tues", 2:"Wed", 3:"Thurs", 4:"Fri", 5:"Sat", 6:"Sun"}
weeks={0:"week 1", 1:"week 2", 2:"week 3", 3:"week 4"}
for i in range(len(id[0])):
    print(days[id[1][i]], "of", weeks[id[0][i]])


the max temp of the day dropped below the avg temp of the month of Nov:  [20 21 25 20 25 23 23 21 25 24 26 22 26 26 25 24]
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3], dtype=int64), array([0, 2, 3, 5, 6, 0, 1, 2, 4, 0, 1, 5, 1, 2, 4, 6], dtype=int64))
Mon of week 1
Wed of week 1
Thurs of week 1
Sat of week 1
Sun of week 1
Mon of week 2
Tues of week 2
Wed of week 2
Fri of week 2
Mon of week 3
Tues of week 3
Sat of week 3
Tues of week 4
Wed of week 4
Fri of week 4
Sun of week 4


In [28]:
c1=a[0, 0:, 0:,0:].reshape(1,56) #first month Nov
c2=a[1, 0:, 0:,0:].reshape(1,56) #second month Dec
c3=a[2, 0:, 0:,0:].reshape(1,56) #third month Jan
c4=a[3, 0:, 0:,0:].reshape(1,56) #fourth month Feb

c5 = np.concatenate((c1,c2,c3,c4)) #concatenate all months individually so that all weeks of the same month must be in one row.
print(c5)

[[  9  20  13  31   8  21  13  25   9  29  15  20  10  25  13  23   9  23
   13  21 -13  32  15  25  13  31  15  29   9  24   6  26  50  30  10  30
    7  30  12  22  11  32  13  30  12  26  15  26  15  29   8  25  11  27
   15  24]
 [  6  20  13  32  13  28  15  25  10  31  12  23  13  30   9  32   6  32
    8  30   7  32   7  32  14  29   9  21  14  23  11  23  14  29  15  23
   15  30  10  31  13  30  13  24  10  29  12  24   6  31  13  31  13  29
    7  25]
 [  8  18   4  19   6  18   2  22   2  18   2   5  21   5   7  20   3  21
    3  20   5  20   3  18   2   6  20   6   4  19   5  21   5  18   5  21
    3  19   7   6  22   4   8  22   2  20   2  22   4  20   7  22   7   2
   22   5]
 [  7  22  10  19 -10  18  11  20   8  20   9  25  22  10   8  22   9  21
   10  22   8  19   9  18  11  11  18  11   8  21  11  20   8  22  10  18
    7  18   7   7  19   7   7  19   9  22   8  22  11  18  12  22   8  11
   21   8]]


In [29]:
# using formulae
feh = (9 * a / 5 + 32)
print("The Following below data in the fahrenheit:\n",feh)

The Following below data in the fahrenheit:
 [[[[ 48.2  68. ]
   [ 55.4  87.8]
   [ 46.4  69.8]
   [ 55.4  77. ]
   [ 48.2  84.2]
   [ 59.   68. ]
   [ 50.   77. ]]

  [[ 55.4  73.4]
   [ 48.2  73.4]
   [ 55.4  69.8]
   [  8.6  89.6]
   [ 59.   77. ]
   [ 55.4  87.8]
   [ 59.   84.2]]

  [[ 48.2  75.2]
   [ 42.8  78.8]
   [122.   86. ]
   [ 50.   86. ]
   [ 44.6  86. ]
   [ 53.6  71.6]
   [ 51.8  89.6]]

  [[ 55.4  86. ]
   [ 53.6  78.8]
   [ 59.   78.8]
   [ 59.   84.2]
   [ 46.4  77. ]
   [ 51.8  80.6]
   [ 59.   75.2]]]


 [[[ 42.8  68. ]
   [ 55.4  89.6]
   [ 55.4  82.4]
   [ 59.   77. ]
   [ 50.   87.8]
   [ 53.6  73.4]
   [ 55.4  86. ]]

  [[ 48.2  89.6]
   [ 42.8  89.6]
   [ 46.4  86. ]
   [ 44.6  89.6]
   [ 44.6  89.6]
   [ 57.2  84.2]
   [ 48.2  69.8]]

  [[ 57.2  73.4]
   [ 51.8  73.4]
   [ 57.2  84.2]
   [ 59.   73.4]
   [ 59.   86. ]
   [ 50.   87.8]
   [ 55.4  86. ]]

  [[ 55.4  75.2]
   [ 50.   84.2]
   [ 53.6  75.2]
   [ 42.8  87.8]
   [ 55.4  87.8]
   [ 55.4  84.2]
   [

In [30]:
d=feh[1,0:,0:,0:]
# c1=feh[1,0, 0:, 0:].mean()
# c2=feh[1,1, 0:, 0:].mean()
# c3=feh[1,2, 0:, 0:].mean()
# c4=feh[1,3, 0:, 0:].mean()
# c5=[c1,c2,c3,c4]
# np.sort(c5)[::-1]
# print(d)
# print(d.shape)
# Calculate the weekly averages for December
dec_weekly_avg = np.mean(d, axis=2)
# print(dec_weekly_avg)
# Calculate the sorting indices in descending order
sorting_indices = np.argsort(np.mean(dec_weekly_avg, axis=1))[::-1]
# print(sorting_indices)

# Sort the weeks based on the sorting indices
sorted_dec_data = d[sorting_indices]

print("Original data for December:\n", d)
print("Sorted data for December based on weekly average:\n", sorted_dec_data)

Original data for December:
 [[[42.8 68. ]
  [55.4 89.6]
  [55.4 82.4]
  [59.  77. ]
  [50.  87.8]
  [53.6 73.4]
  [55.4 86. ]]

 [[48.2 89.6]
  [42.8 89.6]
  [46.4 86. ]
  [44.6 89.6]
  [44.6 89.6]
  [57.2 84.2]
  [48.2 69.8]]

 [[57.2 73.4]
  [51.8 73.4]
  [57.2 84.2]
  [59.  73.4]
  [59.  86. ]
  [50.  87.8]
  [55.4 86. ]]

 [[55.4 75.2]
  [50.  84.2]
  [53.6 75.2]
  [42.8 87.8]
  [55.4 87.8]
  [55.4 84.2]
  [44.6 77. ]]]
Sorted data for December based on weekly average:
 [[[57.2 73.4]
  [51.8 73.4]
  [57.2 84.2]
  [59.  73.4]
  [59.  86. ]
  [50.  87.8]
  [55.4 86. ]]

 [[42.8 68. ]
  [55.4 89.6]
  [55.4 82.4]
  [59.  77. ]
  [50.  87.8]
  [53.6 73.4]
  [55.4 86. ]]

 [[48.2 89.6]
  [42.8 89.6]
  [46.4 86. ]
  [44.6 89.6]
  [44.6 89.6]
  [57.2 84.2]
  [48.2 69.8]]

 [[55.4 75.2]
  [50.  84.2]
  [53.6 75.2]
  [42.8 87.8]
  [55.4 87.8]
  [55.4 84.2]
  [44.6 77. ]]]


In [31]:

winter_avg = np.mean(a[:, :, :, 0:])  

# Extract temperature data for the first three days of each month
first_three_days = a[:, :, :3, 0:]

# Calculate average temperature for the first three days of each month
avg_first_three_days = np.mean(first_three_days, axis=(2, 3))

# Calculate sorting indices in descending order based on the average temperature
sorting_indices = np.argsort(avg_first_three_days)[::-1]

# Sort the months' data based on the sorting indices
sorted_data = a[sorting_indices]

print("Original data for the first three days of each month:\n", first_three_days)
print("Sorted data based on overall average for the whole winter:\n", sorted_data)

Original data for the first three days of each month:
 [[[[  9  20]
   [ 13  31]
   [  8  21]]

  [[ 13  23]
   [  9  23]
   [ 13  21]]

  [[  9  24]
   [  6  26]
   [ 50  30]]

  [[ 13  30]
   [ 12  26]
   [ 15  26]]]


 [[[  6  20]
   [ 13  32]
   [ 13  28]]

  [[  9  32]
   [  6  32]
   [  8  30]]

  [[ 14  23]
   [ 11  23]
   [ 14  29]]

  [[ 13  24]
   [ 10  29]
   [ 12  24]]]


 [[[  8  18]
   [  4  19]
   [  6  18]]

  [[  7  20]
   [  3  21]
   [  3  20]]

  [[  4  19]
   [  5  21]
   [  5  18]]

  [[  8  22]
   [  2  20]
   [  2  22]]]


 [[[  7  22]
   [ 10  19]
   [-10  18]]

  [[  8  22]
   [  9  21]
   [ 10  22]]

  [[  8  21]
   [ 11  20]
   [  8  22]]

  [[  7  19]
   [  9  22]
   [  8  22]]]]
Sorted data based on overall average for the whole winter:
 [[[[[  9  20]
    [ 13  31]
    [  8  21]
    [ 13  25]
    [  9  29]
    [ 15  20]
    [ 10  25]]

   [[ 13  23]
    [  9  23]
    [ 13  21]
    [-13  32]
    [ 15  25]
    [ 13  31]
    [ 15  29]]

   [[  9  24]
    [  6

In [32]:
c1=a[0:,0:,0:,0]
c2=a[0:,0:,0:,1]
c3=c1-c2
print(c3)

[[[-11 -18 -13 -12 -20  -5 -15]
  [-10 -14  -8 -45 -10 -18 -14]
  [-15 -20  20 -20 -23 -10 -21]
  [-17 -14 -11 -14 -17 -16  -9]]

 [[-14 -19 -15 -10 -21 -11 -17]
  [-23 -26 -22 -25 -25 -15 -12]
  [ -9 -12 -15  -8 -15 -21 -17]
  [-11 -19 -12 -25 -18 -16 -18]]

 [[-10 -15 -12 -20 -16  -3  16]
  [-13 -18 -17 -15 -15  -4  14]
  [-15 -16 -13 -16 -16   1  18]
  [-14 -18 -20 -16 -15   5  17]]

 [[-15  -9 -28  -9 -12 -16  12]
  [-14 -12 -12 -11  -9   0   7]
  [-13  -9 -14  -8 -11   0  12]
  [-12 -13 -14  -7 -10  -3  13]]]


In [33]:
# Extract max temperature values for each day
max_temps = a[:, :, :, 1]
print(max_temps.shape)
# Calculate the difference between max temperatures of consecutive days
diff_consecutive_days1 = np.diff(max_temps, axis=2)

print("Difference between max temps of consecutive days:\n", diff_consecutive_days)

(4, 4, 7)


NameError: name 'diff_consecutive_days' is not defined